### ISSUE TITLE
Python 2 and SSL issues (was: DPlay crash)

### ISSUE THREAD

**Issue by lunderhage** [spaam/svtplay-dl#298]
commit e1cb21c20a2fb2b00c25f388e1a795c12d10706c

svtplay-dl -S http://www.dplay.se/sveriges-varsta-kandisbilforare/season-1-kissnodig-av-inbromsning/ --verbose
DEBUG [1446580824.46] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.dplay.se/sveriges-varsta-kandisbilforare/season-1-kissnodig-av-inbromsning/'
DEBUG [1446580824.74] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.dplay.se/api/v2/ajax/videos?video_id=137341'
DEBUG [1446580824.98] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://geo.dplay.se/geo.js'
DEBUG [1446580825.41] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'https://secure.dplay.se/secure/api/v2/user/authorization/stream/137341?stream_type=hds'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 345, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 176, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 202, in get_one_media
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

(I'm on Ubuntu 14.04)

**Comment by olof** [comment]
I'm unable to reproduce (neither on debian stable nor unstable). Can you confirm that this wasn't a temporary issue on their part? Are you able to use the web interface when you're having this issue?

**Comment by lunderhage** [comment]
Tried again and still same problem. Web page works, but I don't have flash installed so I can't watch anything.

**Comment by olof** [comment]
Just fyi, I think you may have hit this bug: https://bugs.launchpad.net/ubuntu/+source/python-requests/+bug/1299075

**Comment by ullgren** [comment]
Manually installing "pip install ndg-httpsclient" did not solve this issue on Ubuntu 14.04

```
$ ./svtplay-dl --version
/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/subj_alt_name.py:22: UserWarning: Error importing pyasn1, subjectAltName check for SSL peer verification will be disabled.  Import error is: No module named pyasn1.type
  warnings.warn(import_error_msg)
/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/ssl_peer_verification.py:25: UserWarning: SubjectAltName support is disabled - check pyasn1 package installation to enable
  warnings.warn(SUBJ_ALT_NAME_SUPPORT_MSG)
/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/subj_alt_name.py:22: UserWarning: Error importing pyasn1, subjectAltName check for SSL peer verification will be disabled.  Import error is: No module named pyasn1.type
  warnings.warn(import_error_msg)
0.20.2015.10.25-10-g4093102

$ ./svtplay-dl --verbose http://www.dplay.se/dessertmastarna/season-3-teknikstafett-och-citrusfrossa/
/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/subj_alt_name.py:22: UserWarning: Error importing pyasn1, subjectAltName check for SSL peer verification will be disabled.  Import error is: No module named pyasn1.type
  warnings.warn(import_error_msg)
/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/ssl_peer_verification.py:25: UserWarning: SubjectAltName support is disabled - check pyasn1 package installation to enable
  warnings.warn(SUBJ_ALT_NAME_SUPPORT_MSG)
/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/subj_alt_name.py:22: UserWarning: Error importing pyasn1, subjectAltName check for SSL peer verification will be disabled.  Import error is: No module named pyasn1.type
  warnings.warn(import_error_msg)
DEBUG [1446628347.89] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.dplay.se/dessertmastarna/season-3-teknikstafett-och-citrusfrossa/'
DEBUG [1446628348.11] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.dplay.se/api/v2/ajax/videos?video_id=137415'
DEBUG [1446628348.32] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://geo.dplay.se/geo.js'
DEBUG [1446628348.37] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'https://secure.dplay.se/secure/api/v2/user/authorization/stream/137415?stream_type=hds'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./svtplay-dl/__main__.py", line 13, in <module>
  File "./svtplay-dl/svtplay_dl/__init__.py", line 345, in main
  File "./svtplay-dl/svtplay_dl/__init__.py", line 176, in get_media
  File "./svtplay-dl/svtplay_dl/__init__.py", line 202, in get_one_media
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by ullgren** [comment]
Also adding  python-pyasn1 seems to solve the problem.

So after 
```
$ sudo -i 
# pip install ndg-httpsclient
# apt-get install python-pyasn1
```

It works.  Thanks for your support.

**Comment by lunderhage** [comment]
Yup, installing those packages solved the problem. Thanks!

**Comment by fredentoft** [comment]
Installed those packages, plus the packages listed in issue #303, still get the same error.

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./svtplay-dl/__main__.py", line 13, in <module>
  File "./svtplay-dl/svtplay_dl/__init__.py", line 345, in main
  File "./svtplay-dl/svtplay_dl/__init__.py", line 174, in get_media
  File "./svtplay-dl/svtplay_dl/__init__.py", line 202, in get_one_media
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by spaam** [comment]
@fredentoft did you install ndg-httpsclient too ?

**Comment by fredentoft** [comment]
Yes I did, forgot to paste that it seems. 
```bash
bow@vishera:~$ pip install ndg-httpsclient
Requirement already satisfied (use --upgrade to upgrade): ndg-httpsclient in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): PyOpenSSL in /usr/lib/python2.7/dist-packages (from ndg-httpsclient)
Cleaning up...
```
I do find it odd that I do not see any reference to it in my verbose output compared to the other posts.

**Comment by spaam** [comment]
strange that  everyone else fixed their issue with that but not you. hmm.

**Comment by fredentoft** [comment]
Very much so.
I don't know if this might help identifying something missing.
```
$ pip freeze
GnuPGInterface==0.3.2
MySQL-python==1.2.3
apt-xapian-index==0.45
argparse==1.2.1
chardet==2.0.1
colorama==0.2.5
dnspython==1.11.1
eyeD3==0.6.18
html5lib==0.999
iotop==0.6
libvirt-python==1.2.2
mercurial==2.8.2
ndg-httpsclient==0.4.0
pdfminer==20110515
pyOpenSSL==0.13
pyasn1==0.1.7
pycrypto==2.6.1
pycups==1.9.66
pycurl==7.19.3
pygobject==3.12.0
pysmbc==1.0.14.1
python-apt==0.9.3.5
python-debian==0.1.21-nmu2ubuntu2
requests==2.2.1
six==1.5.2
ssh-import-id==3.21
svtplay-dl==0.20.2015.11.29
system-service==0.1.6
urllib3==1.7.1
virtualenv==1.11.4
wsgiref==0.1.2
```
Den 1 dec 2015 23:42 skrev "Johan Andersson" <notifications@github.com>:

**Comment by spaam** [comment]
you are running ubuntu 14.04  ?

**Comment by fredentoft** [comment]
Yes
Den 2 dec 2015 00:15 skrev "Johan Andersson" <notifications@github.com>:

**Comment by dentarg** [comment]
Same thing on OS X 10.9.5, I haven't tried installing any of the packages mentioned above (trivia: I encountered this when I was going to check if #307 is still an issues)

```
$ svtplay-dl --version
0.20.2015.11.29

$ svtplay-dl --verbose -S http://www.dplay.se/best-of-buddys/season-2-ung-som-gammal/
DEBUG [1451250964.96] /usr/local/Cellar/svtplay-dl/0.20.2015.11.29/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.dplay.se/best-of-buddys/season-2-ung-som-gammal/'
DEBUG [1451250965.49] /usr/local/Cellar/svtplay-dl/0.20.2015.11.29/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.dplay.se/api/v2/ajax/videos?video_id=130382'
DEBUG [1451250965.53] /usr/local/Cellar/svtplay-dl/0.20.2015.11.29/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://geo.dplay.se/geo.js'
DEBUG [1451250965.98] /usr/local/Cellar/svtplay-dl/0.20.2015.11.29/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'https://secure.dplay.se/secure/api/v2/user/authorization/stream/130382?stream_type=hds'
/usr/local/Cellar/svtplay-dl/0.20.2015.11.29/libexec/vendor/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/Cellar/svtplay-dl/0.20.2015.11.29/libexec/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/0.20.2015.11.29/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 345, in main
    get_media(url, options)
  File "/usr/local/Cellar/svtplay-dl/0.20.2015.11.29/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 176, in get_media
    get_one_media(stream, options)
  File "/usr/local/Cellar/svtplay-dl/0.20.2015.11.29/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 202, in get_one_media
    raise e
requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by spaam** [comment]
in master and next release going to have --dont-verify-ssl-cert bad workaround for this..

**Comment by dentarg** [comment]
> in master and next release going to have --dont-verify-ssl-cert bad workaround for this..

I don't think that's the way to go.

It's a problem for us Python 2.7 users (as the link in @olof's comment above pointed).

[Seems like the packages needed](http://docs.python-requests.org/en/latest/community/updates/#id24) for requests can be installed with:

    pip install requests[security] 

requests haven't yet documented this: https://github.com/kennethreitz/requests/issues/1969#issuecomment-55548135

**Comment by spaam** [comment]
>>in master and next release going to have --dont-verify-ssl-cert bad workaround for this.

>  I don't think that's the way to go.

i know. if we can fix this in a proper way I'm happy to remove it.

**Comment by dentarg** [comment]
> It's a problem for us Python 2.7

I believe it should work on Python 2.7.9+

At https://github.com/kennethreitz/requests/issues/1969#issuecomment-74448949 I saw this comment

> We should also push people towards Python 2.7.9, which addresses this.

and I guess it is referring to [PEP-466](https://www.python.org/dev/peps/pep-0466/) and [PEP 466: backport ssl changes].

My issue was that my Homebrew installed `svtplay-dl` uses my system `python`, which is 2.7.5.

It works for me when I'm using Python 2.7.10 (I haven't manually installed the packages mentioned).

**Comment by spaam** [comment]
@fredentoft what python version do you have? i can't reproduce this on my ubuntu install after i installed the packages @ullgren wrote.    

python 2.7.6 and the same packet versions you have installed.

**Comment by spaam** [comment]
latest version have a fix for this. if you install via setup.py it will install some extra packages if you use 2.7.8 or older.
