### ISSUE TITLE
dashparse throws error on certain svtplay urls.

### ISSUE THREAD

**Issue by jiggstrom** [spaam/svtplay-dl#448]
Hi,
This is the first time I tried to use svtplay-dl, and I ran into some kind of problem with parsing DASH info. Unfortunately I'm not too good at python and my understanding of media stream formats is even worse... But I managed to work around the problem by catching, and ignoring, the exception and removing dash from my list of stream-priorities...

I'll try fixing it later, and if I manage I'll send you a PR.

(The problem is the same on both windows and Ubuntu, .exe version, packed python and unpacked)

Verbose output below:

```
svtplay-dl  --stream-priority=hls,hds,http,rtmp --verbose http://www.svtplay.se/video/2579427/bla-ogon/bla-ogon-sasong-1-avsnitt-5
DEBUG [1473800534.9716964] site-packages\svtplay_dl-1.4-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/2579427/bla-ogon/bla-ogon-sasong-1-avsnitt-5'
DEBUG [1473800535.1630268] site-packages\svtplay_dl-1.4-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svt.se/videoplayer-api/video/1359596-005A'
DEBUG [1473800535.3076448] site-packages\svtplay_dl-1.4-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://svtplay18m-f.akamaihd.net/z/world/open/20160315/1359596-005A/PG-1359596-005A-OGONBLA-04_,988,240,348,456,636,1680,2796,.mp4.csmil/manifest.f4m'
DEBUG [1473800535.517775] site-packages\svtplay_dl-1.4-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://svtplay18i-f.akamaihd.net/i/world/open/20160315/1359596-005A/PG-1359596-005A-OGONBLA-04_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1359596-005A.m3u8'
DEBUG [1473800535.6018896] site-packages\svtplay_dl-1.4-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://switcher.cdn.svt.se/1359596-005A.m3u8'
DEBUG [1473800535.8301945] site-packages\svtplay_dl-1.4-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://ed0.cdn.svt.se/vod/_definst_/amlst:20160315/1359596-005A/PG-1359596-005A-OGONBLA-04/playlist.m3u8'
DEBUG [1473800535.8788486] site-packages\svtplay_dl-1.4-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://svtplay18g-f.akamaihd.net/d/world/open/delivery/20160315/1359596-005A/dash-ondemand/PG-1359596-005A-OGONBLA-04-becc0b97-1666-336d-f493-98e9abe9647e-ondemand.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1359596-005A.mpd'
DEBUG [1473800535.9687548] site-packages\svtplay_dl-1.4-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://switcher.cdn.svt.se/1359596-005A.mpd'
DEBUG [1473800536.2045715] site-packages\svtplay_dl-1.4-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://ed3.cdn.svt.se/vod/_definst_/amlst:20160315/1359596-005A/PG-1359596-005A-OGONBLA-04/manifest.mpd'
ERROR [1473800536.2721221] site-packages\svtplay_dl-1.4-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.4
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "site-packages\svtplay_dl-1.4-py3.5.egg\svtplay_dl\__init__.py", line 444, in main
  File "site-packages\svtplay_dl-1.4-py3.5.egg\svtplay_dl\__init__.py", line 178, in get_media
  File "site-packages\svtplay_dl-1.4-py3.5.egg\svtplay_dl\__init__.py", line 225, in get_one_media
  File "site-packages\svtplay_dl-1.4-py3.5.egg\svtplay_dl\service\svtplay.py", line 119, in get
  File "site-packages\svtplay_dl-1.4-py3.5.egg\svtplay_dl\fetcher\dash.py", line 33, in dashparse
AttributeError: 'NoneType' object has no attribute 'text'
svtplay-dl returned -1
```
Anyway, since I managed to get by, your superb program made my day! Thanks!
Jens

**Comment by Sopor-** [comment]
There seems to be some changes on SVTPlay. Retrospect has also stopped working today.

**Comment by spaam** [comment]
b1859b1f6bd75a7a4 might be the one who broke it, now it gets an .mpd file i dont support

**Comment by Sopor-** [comment]
Is this the same issue or should i create a new one?
```
python svtplay-dl -A http://www.svtplay.se/fangade
ERROR: Couldn't retrieve episode list
```

**Comment by spaam** [comment]
create a new one

**Comment by jiggstrom** [comment]
The program I was downloading isn't available any more, but I managed to find another non-working download. So I grabbed the DASH XML to see what was the problem. And, besides that I haven't seen any working DASH-XML, it seems like the schema has changed... I'll attach the file.

The URL where the error can be reproduced is http://www.svtplay.se/video/8169487/bron/bron-sasong-1-avsnitt-2 it should be available for the next five weeks or so.
[Dash-xml.txt](https://github.com/spaam/svtplay-dl/files/470907/Dash-xml.txt)

**Comment by spaam** [comment]
awesome.  :) i have an idea on how to fix it but its getting late so that will be something for tomorrow :)

**Comment by spaam** [comment]
there is a temp fix for this in master :)

**Comment by jiggstrom** [comment]
Nice! (same thing I did temporary, but I didn't think such a PR would be accepted so I never sent it... 👍 )

**Comment by spaam** [comment]
1.5 is out with a fix for this.
brew will be updated soon.
thanks for the bug report :)

**Comment by rensgr** [comment]
hmmm. it looks like this problem is back. (just newly installed. old install still works......)

URL : https://www.oppetarkiv.se/video/1579805/de-drabbade-avsnitt-5-av-12
( there is others too, who give the same problem: )

Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.4/site-packages/svtplay_dl/__init__.py", line 466, in main
    get_media(urls[0], options)
  File "/usr/lib/python3.4/site-packages/svtplay_dl/__init__.py", line 196, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/lib/python3.4/site-packages/svtplay_dl/__init__.py", line 228, in get_one_media
    if not filename(stream):
  File "/usr/lib/python3.4/site-packages/svtplay_dl/output.py", line 128, in filename
    data = ensure_unicode(stream.get_urldata())
  File "/usr/lib/python3.4/site-packages/svtplay_dl/service/__init__.py", line 31, in get_urldata
    self._urldata = self.http.request("get", self.url).text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by rensgr** [comment]
heres with the -v option. hope this helps....

svtplay-dl -v --force -P hls -S https://www.oppetarkiv.se/video/1579863/de-drabbade-avsnitt-4-av-12DEBUG [1502322863.1064103] /usr/lib/python3.4/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.oppetarkiv.se/video/1579863/de-drabbade-avsnitt-4-av-12'
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.4/site-packages/svtplay_dl/__init__.py", line 466, in main
    get_media(urls[0], options)
  File "/usr/lib/python3.4/site-packages/svtplay_dl/__init__.py", line 196, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/lib/python3.4/site-packages/svtplay_dl/__init__.py", line 228, in get_one_media
    if not filename(stream):
  File "/usr/lib/python3.4/site-packages/svtplay_dl/output.py", line 128, in filename
    data = ensure_unicode(stream.get_urldata())
  File "/usr/lib/python3.4/site-packages/svtplay_dl/service/__init__.py", line 31, in get_urldata
    self._urldata = self.http.request("get", self.url).text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by rensgr** [comment]
hmmm...   this iseems to be python3 related. everything works on 2.7......

sorry.
